#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys
import zipfile

print(sys.argv)
if len(sys.argv)!=3:
    print("need 2 arguments")
    sys.exit()

zip_file = sys.argv[1]
current_path = os.path.abspath('.')
dest_path = sys.argv[2]


print "Processing File " + zip_file
file=zipfile.ZipFile(zip_file,"r");
for name in file.namelist():
    utf8name=name.decode('gbk')
    print "Extracting " + utf8name
    pathname = os.path.dirname(utf8name)
    if not os.path.exists(pathname) and pathname!= "":
        os.makedirs(pathname)
    data = file.read(name)
    if not os.path.exists(utf8name):
        fo = open(utf8name, "w")
        fo.write(data)
        fo.close
file.close()
